acme_account_homepage:
    path:     /
    defaults: { _controller: AccountBundle:Default:index }
acme_account_create:
    path:     /create
    defaults: { _controller: AccountBundle:Default:create }