
parameters:
    app.mailer.transport: sendmail
    app.mailer.template: template

services:
    app.mailer:
        class:        Acme\AccountBundle\Mailer
        arguments:    ['%app.mailer.transport%','%app.mailer.template%']